spring:
  mvc:
    throw-exception-if-no-handler-found: true
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
  profiles:
    active: dev
  messages:
    basename: i18n/messages
  autoconfigure:
    # 启用 JSR-303 校验
    enable: true


